"""English UI copy grouped by the area of the application that uses it."""

COMMON = {
    "loading": "Loading…",
    "retry": "Retry",
    "missing": "—",
    "no_data": "No data for this period",
    "metrics_unavailable": "Metrics temporarily unavailable",
    "couldnt_load_card": "Couldn't load this card",
    "no_visits": "No visits in this period",
    "no_patients": "No out-of-control patients",
    "not_computed": "Not computed yet",
    "status_unavailable": "Status unavailable",
    "updated": "Updated",
    "prev": "Prev",
    "next": "Next",
    "showing_first": "Showing first {limit} of {total}",
    "empty_patient_range": "0-0 of 0",
}

DASHBOARD = {
    "title": "Hypertension & Diabetes Dashboard",
    "visits": "Visits",
    "patient_mix": "Patient Mix",
    "unique_patients": "Unique patients",
    "new_patients": "New patients",
    "returning_patients": "Returning patients",
    "repeat_visit_ratio": "Repeat-visit ratio",
    "hypertension": "Hypertension",
    "diabetes": "Diabetes",
    "comorbid": "Comorbid",
    "clinical_control": "Clinical Control",
    "bp_control": "BP control",
    "glycemic_control": "Glycemic control",
    "normal": "Normal",
    "stage_1": "Stage 1",
    "stage_2": "Stage 2",
    "crisis": "Crisis",
    "glucose_hba1c": "Glucose / HbA1c",
    "average_glucose": "Average glucose",
    "median_glucose": "Median glucose",
    "average_hba1c": "Average HbA1c",
    "median_hba1c": "Median HbA1c",
    "comorbidity": "Comorbidity",
    "data_quality": "Data Quality",
    "files_processed": "Files processed",
    "average_coverage": "Average coverage",
    "rows_seen": "Rows seen",
    "rows_accepted": "Rows accepted",
    "rows_flagged": "Rows flagged",
    "rows_rejected": "Rows rejected",
    "patient_name": "Name",
    "patient_phone_address": "Phone + address",
    "patient_last_visit": "Last visit",
    "patient_latest_readings": "Latest readings",
    "patient_status": "Status",
    "badge_crisis": "Crisis",
    "badge_bp_uncontrolled": "BP uncontrolled",
    "badge_hba1c_uncontrolled": "HbA1c uncontrolled",
    "badge_no_contact": "No contact info",
    "period_1d": "1D",
    "period_3d": "3D",
    "period_1w": "1W",
    "period_2w": "2W",
    "period_1m": "1M",
    "patient_table_title": "Out-of-control patients",
}

ISSUE_CODE_LABELS = {
    "MISSING_REQUIRED_FIELD": "Missing required field",
    "INVALID_DATE": "Invalid date",
    "INVALID_PHONE": "Invalid phone",
    "INVALID_ID": "Invalid ID",
}

UPLOAD = {
    "drop_zone": "Drag and drop CSV or XLSX files here, or click to browse",
    "supports_files": "Supports .csv and .xlsx files",
    "files_ready": "Files Ready ({count})",
    "clear_all": "Clear All",
    "dump_files": "Dump Files",
    "source_column": "Source File Column",
    "target_column": "Target DB Column",
    "target_placeholder": "Target column name...",
    "invalid_format": "Invalid format.",
    "removed": "Removed: {filename}",
    "all_removed": "All files removed.",
    "no_files": "No files uploaded.",
    "failed": "Failed: {filenames}",
    "success": "Success, all files dumped and recorded.",
    "xlsx_badge": "XLSX",
    "csv_badge": "CSV",
}
