"""English UI copy grouped by the area of the application that uses it."""

COMMON = {
    "loading": "Loading…",
    "retry": "Retry",
    "missing": "—",
    "no_data": "No data for this period",
    "metrics_unavailable": "Metrics temporarily unavailable",
    "couldnt_load_card": "Couldn't load this card",
    "unavailable": "Metrics temporarily unavailable",
    "error": "Couldn't load this card",
    "no_visits": "No visits in this period",
    "no_patients": "No out-of-control patients",
    "not_computed": "Not computed yet",
    "status_unavailable": "Status unavailable",
    "updated": "Updated",
    "prev": "Prev",
    "next": "Next",
    "showing_first": "Showing first {limit} of {total}",
    "empty_patient_range": "0-0 of 0",
    "top_issues": "Top issues",
    "readings_bp": "BP",
    "readings_glucose": "Glucose",
    "readings_hba1c": "HbA1c",
}

DASHBOARD = {
    "title": "Hypertension & Diabetes Dashboard",
    "visits": "Visits",
    "patient_mix": "Patient Mix",
    "unique_patients": "Unique patients",
    "new_patients": "New patients",
    "returning_patients": "Returning patients",
    "repeat_visit_ratio": "Repeat-visit ratio",
    "hypertension": "Hypertension",
    "diabetes": "Diabetes",
    "comorbid": "Comorbid",
    "clinical_control": "Clinical Control",
    "bp_control": "BP control",
    "glycemic_control": "Glycemic control",
    "normal": "Normal",
    "stage_1": "Stage 1",
    "stage_2": "Stage 2",
    "crisis": "Crisis",
    "glucose_hba1c": "Glucose / HbA1c",
    "average_glucose": "Average glucose",
    "median_glucose": "Median glucose",
    "average_hba1c": "Average HbA1c",
    "median_hba1c": "Median HbA1c",
    "comorbidity": "Comorbidity",
    "data_quality": "Data Quality",
    "files_processed": "Files processed",
    "average_coverage": "Average coverage",
    "rows_seen": "Rows seen",
    "rows_accepted": "Rows accepted",
    "rows_flagged": "Rows flagged",
    "rows_rejected": "Rows rejected",
    "patient_name": "Name",
    "patient_phone_address": "Phone + address",
    "patient_last_visit": "Last visit",
    "patient_latest_readings": "Latest readings",
    "patient_status": "Status",
    "badge_crisis": "Crisis",
    "badge_bp_uncontrolled": "BP uncontrolled",
    "badge_hba1c_uncontrolled": "HbA1c uncontrolled",
    "badge_no_contact": "No contact info",
    "period_1d": "1D",
    "period_3d": "3D",
    "period_1w": "1W",
    "period_2w": "2W",
    "period_1m": "1M",
    "patient_table_title": "Out-of-control patients",
}

ISSUE_CODE_LABELS = {
    "MISSING_REQUIRED_FIELD": "Missing required field",
    "INVALID_DATE": "Invalid date",
    "INVALID_PHONE": "Invalid phone",
    "INVALID_ID": "Invalid ID",
}

UPLOAD = {
    "fab_label": "Upload files",
    "dialog_title": "Upload files",
    "dialog_description": "Add CSV or XLSX files, review the column mapping, then upload.",
    "close_label": "Close",
    "drop_zone": "Drag and drop CSV or XLSX files here, or click to browse",
    "supports_files": "CSV or XLSX, up to 5 MB per file, 10 files per batch",
    "files_ready": "Files ready ({count} of {max})",
    "clear_all": "Clear all",
    "upload": "Upload",
    "remove_file": "Remove file",
    "kind_csv": "CSV",
    "kind_xlsx": "XLSX",
    "source_column": "Source column",
    "target_column": "Target column",
    "show_mapping": "Show column mapping",
    "hide_mapping": "Hide column mapping",
    "columns_count": "{count} columns",
    "target_placeholder": "Leave blank to ignore",
    "mapping_pending": "Loading suggestions…",
    "err_target_empty": "Target name becomes empty after normalization.",
    "err_target_duplicate": "Target column is duplicated.",
    "stage_ready": "Ready",
    "stage_presigning": "Preparing",
    "stage_uploading": "Uploading",
    "stage_recording": "Recording",
    "failed_presign": "Couldn't prepare this file.",
    "failed_storage": "Couldn't upload this file.",
    "failed_record": "Couldn't record this file.",
    "toast_rejected": "Some files were rejected: {details}",
    "toast_header_failed": "Couldn't read: {details}",
    "header_reason_blank": "blank column header",
    "header_reason_unreadable": "unreadable file",
    "header_reason_encoding": "unsupported text encoding",
    "header_reason_no_columns": "no columns found",
    "toast_fix_mapping": "Fix the highlighted column names before uploading.",
    "toast_partial_failure": "Some files couldn't be uploaded. See the file details below.",
    "toast_success": "Uploaded. Metrics update after processing.",
    "toast_busy": "An upload is in progress.",
}
